name: CI
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 20
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      # - uses: codecov/codecov-action@v3
      #   if: matrix.os == 'ubuntu-latest' && matrix.node-version == 20
      #   with:
      #     fail_ci_if_error: true
